<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Authors>Muhammad Ali Nawaz</Authors>
    <Description>Application services and DTOs for hhSalon.</Description>
    <Nullable>disable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MailKit" Version="4.17.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\hhSalon.Domain\hhSalon.Domain.csproj" />
  </ItemGroup>

</Project>
